### ISSUE TITLE
Seems it can't be installed in windows.

### ISSUE THREAD

**Issue by holyguy** [gwendall/meteor-auth-client-callbacks#1]
When execute "meteor add gwendall:auth-client-callbacks", will appear the error as below:
Error: ENOENT: no such file or directory, open 'd:\temp\mt-mu2bmn\os\packages\gwendall_auth-client-callbacks.js.map' at Error (native)

And i found there's a blank space or a special character in the temporary file 'gwendallauth-client-callbacks.js.map' in the OS temporary folder 'd:\temp\mt-mu2bmn\os\packages\'.

Maybe it can not support windows platform or some reason?

**Comment by mikothegm** [comment]
I dunno if the author is available to update the code, but you can take the contents of the client/lib.js file in the repo and save it to a .js file in your client code and import the file. If you do that you will get the same Accounts.onLogin() and Accounts.onLogout() functions from adding the package. I was able to use this as a workaround to a project I'm working on today.

**Comment by holyguy** [comment]
@miko3ed  Thanks. I moved to use it in Linux platform. Everything is ok.
